import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/homecomponents/Header";
import { Footer } from "@/components/homecomponents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-neutral-100 md:min-w-[768px] lg:min-w-[1192px] min-h-screen w-fit mx-auto  ${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased font-nunito`}
      >
        <Header />

        {children}
        <footer className="lg:max-w-[1120px] mx-auto">
        <Footer />
      </footer>
      </body>
    </html>
  );
}
